# Generated by Django 4.0.3 on 2022-03-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivelloApp', '0002_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
