# Generated by Django 4.0.3 on 2022-03-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivelloApp', '0004_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='machine',
            name='type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
    ]
