# Generated by Django 4.0.3 on 2022-03-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VivelloApp', '0009_machinetype_vehicletype_vehicle_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field',
        ),
    ]
