# Generated by Django 4.0.3 on 2022-03-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivelloApp', '0011_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='machine',
            field=models.ManyToManyField(blank=True, to='VivelloApp.machine'),
        ),
        migrations.AddField(
            model_name='farm',
            name='vehicle',
            field=models.ManyToManyField(blank=True, to='VivelloApp.vehicle'),
        ),
    ]
