# Generated by Django 4.0.3 on 2022-03-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivelloApp', '0012_farm_machine_farm_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('crop', models.ManyToManyField(blank=True, to='VivelloApp.crop')),
                ('field', models.ManyToManyField(to='VivelloApp.field')),
                ('machine', models.ManyToManyField(to='VivelloApp.machine')),
                ('vehicle', models.ManyToManyField(to='VivelloApp.vehicle')),
            ],
        ),
    ]
