# Generated by Django 4.0.3 on 2022-03-13 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VivelloApp', '0015_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='employee',
        ),
        migrations.AddField(
            model_name='farm',
            name='employee',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
