# Generated by Django 4.0.3 on 2022-03-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivelloApp', '0018_alter_farm_employee_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='field',
            field=models.ManyToManyField(blank=True, to='VivelloApp.field'),
        ),
        migrations.AlterField(
            model_name='task',
            name='machine',
            field=models.ManyToManyField(blank=True, to='VivelloApp.machine'),
        ),
        migrations.AlterField(
            model_name='task',
            name='vehicle',
            field=models.ManyToManyField(blank=True, to='VivelloApp.vehicle'),
        ),
    ]
